<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rex.Media.Codecs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rex.Media.Tests" />
    <InternalsVisibleTo Include="Rex.Media.Codecs.Software" />
    <InternalsVisibleTo Include="Rex.Media.Containers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rex.Media.Primitives\Rex.Media.Primitives.csproj" />
  </ItemGroup>

</Project>
