<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Rex.Fuzz</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpFuzz" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rex.Media.TestKit\Rex.Media.TestKit.csproj" />
  </ItemGroup>

</Project>
