using System.Text;
using Rex.Media.AppCore.Player;
using Rex.Media.Library.Playlists;
using Rex.Media.TestKit;

namespace Rex.Media.Tests.Repository;

/// <summary>
/// The installer offers rexplayer in Explorer's "Open with" for every file it plays (§6.13), from
/// installer/associations.iss. That file is made here from the player's own lists, so the two never
/// drift apart; set REXPLAYER_WRITE_DOCS=1 to rewrite it.
/// </summary>
public sealed class InstallerAssociationTests
{
    private const string Capabilities = @"Software\REX Technologies\rexplayer\Capabilities";

    /// <summary>The kinds of file, each a ProgID with its own name in Explorer, and their extensions.</summary>
    private static readonly (string ProgId, string Kind, IReadOnlyList<string> Extensions)[] Kinds =
    [
        ("rexplayer.video", "Video", MediaFiles.Video),
        ("rexplayer.audio", "Audio", MediaFiles.Audio),
        ("rexplayer.playlist", "Playlist", PlaylistFiles.Extensions),
    ];

    private static string Expected()
    {
        // In Inno Setup, a quote inside a quoted value is doubled.
        const string Open = "\"\"\"{app}\\{#AppExe}\"\" \"\"%1\"\"\"";
        var text = new StringBuilder();
        void Line(string line) => text.Append(line).Append('\n');

        Line("; Generated by InstallerAssociationTests from the lists of files rexplayer plays; do not edit by hand.");
        Line("; Everything is per user and offered, never imposed: rexplayer joins Explorer's \"Open with\" and");
        Line("; Windows' Default apps, and no file type's existing default is changed.");
        Line("[Registry]");
        foreach (var (progId, kind, _) in Kinds)
        {
            var key = @"Software\Classes\" + progId;
            Line($"Root: HKA; Subkey: \"{key}\"; ValueType: string; ValueData: \"{kind}\"; Flags: uninsdeletekey");
            Line($"Root: HKA; Subkey: \"{key}\"; ValueType: string; ValueName: \"FriendlyTypeName\"; ValueData: \"{kind} (rexplayer)\"");
            Line($"Root: HKA; Subkey: \"{key}\\DefaultIcon\"; ValueType: string; ValueData: \"{{app}}\\{{#AppExe}},0\"");
            Line($"Root: HKA; Subkey: \"{key}\\shell\\open\\command\"; ValueType: string; ValueData: {Open}");
        }

        Line("Root: HKA; Subkey: \"Software\\Classes\\Applications\\{#AppExe}\"; ValueType: string; ValueName: \"FriendlyAppName\"; ValueData: \"rexplayer\"; Flags: uninsdeletekey");
        Line("Root: HKA; Subkey: \"Software\\Classes\\Applications\\{#AppExe}\\DefaultIcon\"; ValueType: string; ValueData: \"{app}\\{#AppExe},0\"");
        Line($"Root: HKA; Subkey: \"Software\\Classes\\Applications\\{{#AppExe}}\\shell\\open\\command\"; ValueType: string; ValueData: {Open}");
        Line($"Root: HKA; Subkey: \"{Capabilities}\"; ValueType: string; ValueName: \"ApplicationName\"; ValueData: \"rexplayer\"; Flags: uninsdeletekey");
        Line($"Root: HKA; Subkey: \"{Capabilities}\"; ValueType: string; ValueName: \"ApplicationDescription\"; ValueData: \"A media player for every file, by REX Technologies.\"");
        Line($"Root: HKA; Subkey: \"Software\\RegisteredApplications\"; ValueType: string; ValueName: \"rexplayer\"; ValueData: \"{Capabilities}\"; Flags: uninsdeletevalue");
        foreach (var (progId, _, extensions) in Kinds)
        {
            foreach (var extension in extensions)
            {
                Line($"Root: HKA; Subkey: \"Software\\Classes\\Applications\\{{#AppExe}}\\SupportedTypes\"; ValueType: string; ValueName: \"{extension}\"; ValueData: \"\"");
                Line($"Root: HKA; Subkey: \"Software\\Classes\\{extension}\\OpenWithProgids\"; ValueType: string; ValueName: \"{progId}\"; ValueData: \"\"; Flags: uninsdeletevalue");
                Line($"Root: HKA; Subkey: \"{Capabilities}\\FileAssociations\"; ValueType: string; ValueName: \"{extension}\"; ValueData: \"{progId}\"");
            }
        }

        return text.ToString();
    }

    [Fact]
    [Capability("WIN-02")]
    public void TheInstallerOffersRexplayerForEveryFileItPlays()
    {
        var path = RepoPaths.Combine("installer", "associations.iss");
        var expected = Expected();
        if (Environment.GetEnvironmentVariable("REXPLAYER_WRITE_DOCS") == "1")
        {
            File.WriteAllText(path, expected.Replace("\n", "\r\n", StringComparison.Ordinal));
        }

        Assert.True(File.Exists(path) && File.ReadAllText(path).ReplaceLineEndings("\n") == expected, "installer/associations.iss is out of date; run the tests with REXPLAYER_WRITE_DOCS=1.");
        var script = File.ReadAllText(RepoPaths.Combine("installer", "rexplayer.iss"));
        Assert.Contains("#include \"associations.iss\"", script, StringComparison.Ordinal);
        Assert.Contains("ChangesAssociations=yes", script, StringComparison.Ordinal);
    }

    [Fact]
    public void NoExtensionIsClaimedTwice()
    {
        var all = Kinds.SelectMany(kind => kind.Extensions).ToList();
        Assert.Equal(all.Count, all.Distinct(StringComparer.OrdinalIgnoreCase).Count());
        Assert.All(all, extension => Assert.Matches("^\\.[a-z0-9]+$", extension));
    }
}
