<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rex.Media.Containers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rex.Media.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rex.Media.Primitives\Rex.Media.Primitives.csproj" />
    <ProjectReference Include="..\Rex.Media.IO\Rex.Media.IO.csproj" />
    <ProjectReference Include="..\Rex.Media.Codecs\Rex.Media.Codecs.csproj" />
  </ItemGroup>

</Project>
