<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rex.Media.TestKit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rex.Media.Primitives\Rex.Media.Primitives.csproj" />
    <ProjectReference Include="..\..\src\Rex.Media.Audio\Rex.Media.Audio.csproj" />
  </ItemGroup>

</Project>
